# Generated by Django 4.2.1 on 2023-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='freecount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('used', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='genip_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('temperature', models.CharField(max_length=255)),
                ('input', models.CharField(max_length=100000)),
                ('language', models.CharField(max_length=255)),
                ('output_1st', models.CharField(max_length=500000)),
                ('output_2nd', models.CharField(max_length=500000)),
                ('rate', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(verbose_name='Time Stamp')),
                ('ip', models.CharField(max_length=30)),
                ('free', models.IntegerField(default=0)),
            ],
        ),
    ]
