# Generated by Django 4.2.1 on 2023-06-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genip_db',
            name='duration1',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genip_db',
            name='duration2',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genip_db',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
